[% USE loc -%]
[% IF pages.count<2 %][% RETURN %][% END -%]
[% UNLESS pages.pagearg -%]
    [% pages.pagearg=SESSION.PAGER_SLUG_ENTRY || '.p' -%]
[% END -%]
[% UNLESS base -%]
    [% pages.url=SESSION.CURRENT_PAGE.clone().to_string() -%]
    [% IF (matches = pages.url.match('\.[A-Za-z]+$', 1)) -%]
        [% pages.url = pages.url | remove('\.[A-Za-z]+$') -%]
        [% z=(pages.pageext = matches.0) UNLESS pages.pageext -%]
    [% END -%][%  %]
    [% IF pages.pagearg && (matches = pages.url.match(pages.pagearg _ '\d+$', 1)) -%]
        [% UNLESS pages.current -%]
            [% pages.current = matches.0 -%]
            [% pages.current = pages.current.remove('^' _ pages.pagearg) -%]
        [% END -%]
        [% pages.url = pages.url.remove(pages.pagearg _ '\d+$') -%]
    [% END -%]
[% END -%]
[% z=(pages.current = 1) UNLESS pages.current #fckin magic :) -%]
[% UNLESS pages.pageext -%]
    [% pages.pageext=SESSION.EXTENSIONS_PAGE || '.html' -%]
[% END -%]
[% z=(pages.start = 1) UNLESS pages.start #--//-- -%]
[% IF pages.start>1 -%]
    <a href="[% pages.url | html %][% pages.pageext | html %]">&laquo; [% loc('First') %]</a>
    <a href="[% pages.url | html %][% p_arg | html %][% -1 + pages.start %][% pages.pageext | html %]">&lt;</a>
[% END -%]
[% z=(pages.stop = pages.count) UNLESS pages.stop #--//-- -%]
[% FOREACH p=[pages.start .. pages.stop] -%]
    [% IF p==pages.current -%]
        <b>[[% p %]]</b>
    [% ELSE -%]
        [% p_num=p %]
        [% p_arg=pages.pagearg %]
        [% UNLESS pages.dontcut_first -%]
            [% IF p==1 -%]
                [% p_arg=p_num='' -%]
            [% END -%]
        [% END -%]
        <a href="[% pages.url | html %][% p_arg | html %][% p_num %][% pages.pageext | html %]">[[% p %]]</a>
    [% END -%]
[% END -%]
[% IF pages.count>pages.stop -%]
    <a href="[% pages.url | html %][% p_arg | html %][% pages.stop + 1 %][% pages.pageext | html %]">&gt;</a>
    <a href="[% pages.url | html %][% p_arg | html %][% pages.count %][% pages.pageext | html %]">[% loc('Last') %] &raquo;</a>
[% END -%]
