[% USE loc -%]
[% IF count<2 %][% RETURN %][% END -%]
[% UNLESS pagearg -%]
    [% pagearg=SESSION.PAGER_SLUG_ENTRY || '.p' -%]
[% END -%]
[% UNLESS base -%]
    [% base=SESSION.CURRENT_PAGE.clone().to_string() -%]
    [% IF (matches = base.match('\.[A-Za-z]+$')) -%]
        [% base = base | remove('\.\w+$') -%]
        [% pageext = matches.0 UNLESS pageext -%]
    [% END -%]
    [% IF pagearg && (matches = name.match(pagearg _ '\d+$')) -%]
        [% base = base | remove(pagearg _ '\d+$') -%]
    [% END -%]
[% END -%]
[% UNLESS pageext -%]
    [% pageext=SESSION.EXTENSIONS_PAGE || '.html' -%]
[% END -%]
[% FOREACH p=[1 .. count] -%]
    [% IF p==page_num -%]
        <b>[[% p %]]</b>
    [% ELSE -%]
        [% p_num=p %]
        [% p_arg=pagearg %]
        [% UNLESS dontcut_first -%]
            [% IF p==1 -%]
                [% p_arg=p_num='' -%]
            [% END -%]
        [% END -%]
        <a href="[% base | html %][% p_arg | html %][% p_num %][% pageext | html %]">[[% p %]]</a>
    [% END -%]
[% END -%]
